name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: call-reusable-workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
         node: 14
      
      
