name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: call-reusable-workflow
        run: |
            call-reusable-workflow:
             strategy:
               matrix:
                 nodeversion: [14, 16, 18, 20]
                 uses: ./.github/workflows/reusable-workflow.yml
                 with:
                    node: ${{ matrix.nodeversion }}
          
